### ISSUE TITLE
Wrong default path for RACK_DIR in Makefile

### ISSUE THREAD

**Issue by zebulon-1st** [Geekachuqt/3HR#3]
In the makefile, you wrote :
```
# If RACK_DIR is not defined when calling the Makefile, default to two directories above
RACK_DIR ?= ../
```
Which is wrong, this make an error on build :
```
Makefile:23: ..//plugin.mk: file or directory missing
make: *** no rule to build « ..//plugin.mk ». stop.
```

The good default path is -- _two directories above_ -- seen in other Makefile's Rack plugin projects :
`RACK_DIR ?= ../..`

Best regards ;)

**Comment by Geekachuqt** [comment]
This isn't quite right - whether it will cause an error on build or not will depend on from where you are building.

If I change this to the default path, it causes an error on build for me, per example, with the way I work. However, I can see a point in keeping this default, as I would imagine most people use the default path.
